import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <img src="" alt="" />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi
            nemo architecto cumque quisquam, itaque molestias perferendis
            adipisci, explicabo modi nam aliquam distinctio quia eius illo
            impedit corrupti harum, dolore quo incidunt. Incidunt quaerat odio
            asperiores aliquid? Repellendus, suscipit, quidem quam facilis
            maiores aliquam praesentium laboriosam et dolore magni, consectetur
            adipisci.
          </p>
        </a>
        <a href="">
          <img src="" alt="" />
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi
            nemo architecto cumque quisquam, itaque molestias perferendis
            adipisci, explicabo modi nam aliquam distinctio quia eius illo
            impedit corrupti harum, dolore quo incidunt. Incidunt quaerat odio
            asperiores aliquid? Repellendus, suscipit, quidem quam facilis
            maiores aliquam praesentium laboriosam et dolore magni, consectetur
            adipisci.
          </p>
        </a>
        <a href="">
          <img src="" alt="" />
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi
            nemo architecto cumque quisquam, itaque molestias perferendis
            adipisci, explicabo modi nam aliquam distinctio quia eius illo
            impedit corrupti harum, dolore quo incidunt. Incidunt quaerat odio
            asperiores aliquid? Repellendus, suscipit, quidem quam facilis
            maiores aliquam praesentium laboriosam et dolore magni, consectetur
            adipisci.
          </p>
        </a>
      </main>

      <footer className={styles.footer}>
        &copy; 2022 Time to Code - A Project build with Nextjs
      </footer>
    </div>
  );
}
